### PR TITLE
fix/refactor

### PR DESCRIPTION
**Pull request by vaidas-lungis**
a little bit friday refactoring

put code to functions so it can be tested or just for meaningful name

### CODE REVIEW

**Comment by zygintas** [comment]
gif_im_color_128_b41d1732e0

**Comment by vaidas-lungis** [comment]
https://www.quora.com/How-is-writing-code-like-writing-poetry

**Comment by 4Giedrius** [comment]
`getApplicableItems()` could be Trait or method in `Coupon` class.

**Comment by vaidas-lungis** [comment]
@4Giedrius  yes indeed!

**Pull request merged**
